all: quicksort_0 mergesort_0 insertionsort_0 quicksort_3 mergesort_3 insertionsort_3

quicksort_0: quicksort.cpp
	g++ -O0 quicksort.cpp -o quicksort_0

mergesort_0: mergesort.cpp
	g++ -O0 mergesort.cpp -o mergesort_0

insertionsort_0: insertionsort.cpp
	g++ -O0 insertionsort.cpp -o insertionsort_0

quicksort_3: quicksort.cpp
	g++ -O3 quicksort.cpp -o quicksort_3

mergesort_3: mergesort.cpp
	g++ -O3 mergesort.cpp -o mergesort_3

insertionsort_3: insertionsort.cpp
	g++ -O3 insertionsort.cpp -o insertionsort_3

